trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
# Install OWASP ZAP
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    sudo apt-get update
    sudo apt-get install zaproxy
  displayName: 'Install OWASP ZAP'

# Start OWASP ZAP in daemon mode
- script: |
    zap.sh -daemon -config api.disablekey=true
  displayName: 'Start OWASP ZAP'

# Run the ZAP scan
- script: |
    zap-full-scan.py -t http://your-app-url -r zap_report.html
  displayName: 'Run ZAP Scan'

# Publish the scan results
- task: PublishPipelineArtifact@1
  inputs:
    targetPath: 'zap_report.html'
    artifact: 'ZAPReport'
    publishLocation: 'pipeline'
  displayName: 'Publish ZAP Report'
